### ISSUE TITLE
custom messages not working for input type='text'

### ISSUE THREAD

**Issue by ninjajs** [maestrooo/ember-cli-html5-validation#10]
Setting title attribute but not working for input type='text'. It does work for input type='checkbox' however.

{{input type="text" placeholder="Email" valueBinding="email" required='required' title='custom error message'}}

**Comment by bakura10** [comment]
Hi,

As per spec, the "title" attribute is only used when the "pattern" validation is failing. If you set a pattern attribute it will display the title. However, as you have "required", the first validation rule will be the required.
