### ISSUE TITLE
Could not find module `ember-cli-html5-validation/ext/checkbox`

### ISSUE THREAD

**Issue by tspacek** [maestrooo/ember-cli-html5-validation#12]
On Ember 1.10 - 1.110-beta.4, and on Ember CLi 0.1.8 - 0.2.0-beta.1 I get

```
Could not find module `ember-cli-html5-validation/ext/checkbox` imported from `dashboard/initializers/html5-validation`
```

It's most likely not to be an issue with this addon, rather something with my combination of packages, but I was wondering if anyone else is experiencing the same?

**Comment by bakura10** [comment]
Hi,

I'm using it with Ember 1.11.0-beta3 and Ember-Cli 0.1.15 and I do not have this issue.

Are you using the very latest version of the addon ? (0.0.16) ?

**Comment by tspacek** [comment]
Yeah, `0.0.16` of this addon. I double-checked CLI 0.1.15 and I'm still getting the same, so it must be something else in my project. Thanks.

**Comment by bakura10** [comment]
Sorry I cannot help more :'(. Can you please check in your node_modules folder that the whole addon was properly installed?

**Comment by tspacek** [comment]
Yeah it's all there and commenting out the imports at the top of its initializer stops the error (but breaks the functionality). So there must be something specific to my project results in modules from addons' 'addon' folders not loading.

**Comment by bakura10** [comment]
It seems. Sorry, I'm not an expert of how Ember-Cli internals work :/. You should ask in the forum (discuss.emberjs.com)

**Comment by tspacek** [comment]
Turns out it was completely unrelated: it was due to ember-easy-form not compiling templates correctly in Ember 1.10+. Somehow that resulted in the error above when running `ember test`. Fixed by switching to https://github.com/sir-dunxalot/ember-easy-form-extensions

Thanks for your help, and wonderful addon.

**Comment by bakura10** [comment]
Thanks,

I can't emphasize enough though that Ember-Cli-HTML5-Validation must only be used if you need lightweight validation rules. If your project relies heavily on form, you'd better use something like Ember-Validations ;).
