### ISSUE TITLE
addon causing phantom tests to hang

### ISSUE THREAD

**Issue by shidel-dev** [maestrooo/ember-cli-html5-validation#16]
I included your addon into my application.   It is causing my phantomjs unit tests to hang and not proceed.

I am using: 
ember cli: 0.2.7
ember: 1.13

it seems somewhat similar to https://github.com/babel/ember-cli-babel/issues/29

**Comment by bakura10** [comment]
There was a small issue due to usage of backtick, that has been solved in v0.0.18 of the addon. Could you please try again?

**Comment by bakura10** [comment]
I'm closing for now. A rewritten version of this library has been rewritten to have support with EmberJS 2.
