### ISSUE TITLE
isLoading does not disable Async button

### ISSUE THREAD

**Issue by cracell** [maestrooo/ember-cli-html5-validation#18]
From the readme 
> Note: the async-button component will automatically add the disabled attribute when isValid is false.

Why not also add the disabled attribute when isLoading is true? I want to prevent users from double clicking the submit button and as the async button currently works I can easily send double or triple requests.

My work around is to hookup isValid to a component level method that just sets it to false if isLoading is true but wondering if this could be the default behavior.

Happy to writeup a patch if the behavior is desired.

**Comment by bakura10** [comment]
Hi !

Yes that sounds like a very good idea! Please do a PR and I'll be happy to merge that!

Envoyé de mon iPhone
