### ISSUE TITLE
Change error element to customizable component

### ISSUE THREAD

**Issue by srsgores** [maestrooo/ember-cli-html5-validation#2]
While [the current implementation](https://github.com/maestrooo/ember-cli-html5-validation/blob/master/addon/mixins/validatable-input.js#L156) works, using a ``<p>`` tag, the error message is probably better off as a ``<label>`` element, with a ``for={{inputID}}``.

The current implementation also lacks proper ``aria`` roles: in this case, the ``<p>`` element should have the ``role="alert"`` on it, [as in the example here](http://www.w3.org/WAI/GL/wiki/Using_ARIA_role_of_alert_for_Error_Feedback_in_Forms).

Perhaps, in the future, you could allow users to override the component template entirely...

I am willing to contribute these accessibility changes, if you approve.

**Comment by bakura10** [comment]
This component has been rewritten in v0.1.* and is now a bit more verbose but allow for greater control on how to render errors. Do not hesitate to check the documentation.
