### ISSUE TITLE
If an error occurs in form action then page reloads

### ISSUE THREAD

**Issue by mcm-ham** [maestrooo/ember-cli-html5-validation#21]
Example
```html
// template
{{#validatable-form class="form-horizontal" action="save"}}
  <button>test</button>
{{/validatable-form}}
```
```js
// controller
save() {
    throw new Error("test");
}
```

I think modiyfing:
https://github.com/maestrooo/ember-cli-html5-validation/blob/master/addon/components/validatable-form.js#L33

To this would help:
```js
submit: function(event) {
  event.preventDefault();
  ...
  return false;
},
```

**Comment by mcm-ham** [comment]
Note I've added this workaround to my project but have been seeing errors `Cannot read property 'preventDefault' of undefined` that I can't reproduce so I guess the code should be:
```js
submit: function(event) {
  if (event) { event.preventDefault(); }
  ...
  return false;
},
```

**Comment by bakura10** [comment]
This project has been rewritten and now uses the new mechanism for handling action at the form level. So your action can now return a promise for instance, for greater control.
