### ISSUE TITLE
Form submission will be prevented if any errors are encountered - not working

### ISSUE THREAD

**Issue by iamalex2** [maestrooo/ember-cli-html5-validation#23]
Have the {{#validatable-form action="save"}}  {{/validatable-form}} around my form but not working for me.

I have separate components that are pulled into the form and even tried putting on the actual component. but still form is save and not prevented if not filled in.

Any suggestions.  Still trying to learn the workings of ember-cli  using version 0.2.5

**Comment by bakura10** [comment]
This addon has been rewritten, do not hesitate to evaluate it again, and if you encounter any issue, I'd be happy to assist :).
