### ISSUE TITLE
Does this code remove all event listeners on this element (not just ones added by this addon)?

### ISSUE THREAD

**Issue by mattmarcum** [maestrooo/ember-cli-html5-validation#25]
https://github.com/maestrooo/ember-cli-html5-validation/blob/master/addon/mixins/validatable-input.js#L100

I'm thinking it does, but I could be wrong.  If it does then it might not play nice with other addons or a developer's own customizations of these components.  I think just adding namespaces to your `on` jquery calls will fix this and make it easier to just remove all your event listeners.

**Comment by bakura10** [comment]
Very good catch.

I'm not doing any emberJS work at the moment but I'll see today if I can modify this.

**Comment by Charizard** [comment]
Any status on this?

**Comment by bakura10** [comment]
Nope sorry :(. Feel free to submit a PR for that, I'd be happy to review and merge though.

**Comment by bakura10** [comment]
Just to let you know @Charizard I've updated this library to EmberJS 2. However it's quite different from the original version.

It's still focused on HTML5 validation, but it's now a bit more verbose to give you more flexibility about how elements are rendered.
