### ISSUE TITLE
Min validation doesn't seem to work

### ISSUE THREAD

**Issue by Charizard** [maestrooo/ember-cli-html5-validation#27]
The [HTML 5 Min](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-min) validation is not working.

My form looks like,

``` handlebars
{{#validatable-form action="createAccount" class="paper-form-box"}}
  {{input placeholder='Password'  type='password' value=password required=true min="6"}}
  {{input placeholder='Confirm Password'  type='password' value=passwordConfirmation required=true min=6}}
{{/validatable-form}}
```

The required validation is happening correctly. But the `min` validation doesn't seem to work at all.

PS: I tried both number and string as value for `min`.

**Comment by bakura10** [comment]
Hi,

Sorry for the very late answer. Actually, I'm not sure but I think that the "min" and "max" validators are run by browsers only for elements of type "number".

**Comment by Charizard** [comment]
That is so stupid of me. Sorry for the issue :grimacing:
