### ISSUE TITLE
Allow "keydown" validation for individual inputs

### ISSUE THREAD

**Issue by srsgores** [maestrooo/ember-cli-html5-validation#3]
It would be nice to achieve instant validation on an input, simply by specifying on the element:

```
<label for = "username">Username</label>
{{input type="email" valueBinding="username" id="username" placeholder="Username" required="required" autofocus="autofocus" autocomplete="email" validateOn="keydown"}}
```

Where the ``validateOn="keydown"`` denotes that the validation on that individual input should occur whenever the user presses a key while focused on that input.

I am open to other suggestions on how to override this functionality.  Feedback appreciated.

**Comment by bakura10** [comment]
I'm closing that for now :).
